name: azml-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=23.3
  - pip:
    - azure-ai-ml==1.20.0
    - azure-identity==1.18.0
    - mltable==1.6.1
    - azure-keyvault-secrets==4.9.0
    - numpy==1.21.6
    - scikit-learn==1.2.2
    - scipy==1.7.3
    - pandas==1.3.5
    - azureml-core==1.57.0.post3
    - azureml-telemetry==1.57.0
    - azureml-mlflow==1.57.0
    - cryptography==43.0.1
    - certifi==2024.8.30
    - urllib3==2.2.3
    - paramiko==3.5.0
    - idna==3.10
    - tqdm==4.66.5
    - mlflow==1.26.1
    - protobuf==4.23.4
    - psutil>=5.8,<5.9
    - azureml-inference-server-http  # **Added for deployment**
